# Importing Libraries

In [426]:
import pandas as pd
import matplotlib.pyplot as plt

In [427]:
# Percentage of Missing Values
def per_miss_val(df):
  return 100 * df.isnull().sum() / len(df)

In [428]:
# Read Dataset
df = pd.read_csv('Datasets/india_housing_prices.csv')

In [429]:
# First 5 rows
df.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [430]:
# Last 5 Rows
df.tail()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
249995,249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249996,249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249997,249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249998,249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
249999,250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [431]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

## Data Cleaning and Preprocessing for EDA

In [432]:
# Checking for missing/null values in the dataframe
per = per_miss_val(df)
print(per)

ID                                0.0
State                             0.0
City                              0.0
Locality                          0.0
Property_Type                     0.0
BHK                               0.0
Size_in_SqFt                      0.0
Price_in_Lakhs                    0.0
Price_per_SqFt                    0.0
Year_Built                        0.0
Furnished_Status                  0.0
Floor_No                          0.0
Total_Floors                      0.0
Age_of_Property                   0.0
Nearby_Schools                    0.0
Nearby_Hospitals                  0.0
Public_Transport_Accessibility    0.0
Parking_Space                     0.0
Security                          0.0
Amenities                         0.0
Facing                            0.0
Owner_Type                        0.0
Availability_Status               0.0
dtype: float64

No null values identified in the data.

### ID Column

In [433]:
# Checking for unique IDs
pd.unique(df['ID']).shape

(250000,)

In [434]:
# Checking for datatype consistency
df['ID'].apply(type).unique()

array([<class 'int'>], dtype=object)

In [435]:
# Percentage of missing values
per = per_miss_val(df['ID'])
print(per)

0.0

### Property Location Columns

In [436]:
# State Column
print("Property State Stats")
print(df['State'].describe())
print('')
# States Present in the dataset
print(f"States List: {df['State'].unique()}")

Property State Stats
count     250000
unique        20
top       Odisha
freq       12681
Name: State, dtype: object

States List: ['Tamil Nadu' 'Maharashtra' 'Punjab' 'Rajasthan' 'West Bengal'
 'Chhattisgarh' 'Delhi' 'Jharkhand' 'Telangana' 'Karnataka'
 'Uttar Pradesh' 'Assam' 'Uttarakhand' 'Bihar' 'Gujarat' 'Haryana'
 'Andhra Pradesh' 'Madhya Pradesh' 'Kerala' 'Odisha']

In [437]:
# Checking for datatype consistency
dtypes = list(df['State'].apply(type).unique())
print(f"Datatypes present in State column: {dtypes}")

Datatypes present in State column: [<class 'str'>]

In [438]:
# City Column
print("Property City Stats")
print(df['City'].describe())
print('')
# Cities Present in the dataset
print(f"City List: {df['City'].unique()}")

Property City Stats
count         250000
unique            42
top       Coimbatore
freq            6461
Name: City, dtype: object

City List: ['Chennai' 'Pune' 'Ludhiana' 'Jodhpur' 'Jaipur' 'Durgapur' 'Coimbatore'
 'Bilaspur' 'New Delhi' 'Ranchi' 'Warangal' 'Bangalore' 'Nagpur' 'Lucknow'
 'Silchar' 'Dehradun' 'Noida' 'Gaya' 'Jamshedpur' 'Ahmedabad' 'Hyderabad'
 'Faridabad' 'Amritsar' 'Kolkata' 'Dwarka' 'Vishakhapatnam' 'Bhopal'
 'Indore' 'Haridwar' 'Mysore' 'Patna' 'Raipur' 'Vijayawada' 'Trivandrum'
 'Kochi' 'Surat' 'Gurgaon' 'Mangalore' 'Cuttack' 'Bhubaneswar' 'Guwahati'
 'Mumbai']

In [439]:
# Locality Column
print('Property Locality Stats')
print(df['Locality'].describe())
print('')
# List of localities
print("Locality List")
df['Locality'].unique()

Property Locality Stats
count           250000
unique             500
top       Locality_296
freq               567
Name: Locality, dtype: object

Locality List

array(['Locality_84', 'Locality_490', 'Locality_167', 'Locality_393',
       'Locality_466', 'Locality_246', 'Locality_254', 'Locality_232',
       'Locality_122', 'Locality_75', 'Locality_462', 'Locality_227',
       'Locality_287', 'Locality_148', 'Locality_369', 'Locality_265',
       'Locality_50', 'Locality_385', 'Locality_241', 'Locality_286',
       'Locality_74', 'Locality_459', 'Locality_355', 'Locality_151',
       'Locality_159', 'Locality_382', 'Locality_143', 'Locality_454',
       'Locality_262', 'Locality_136', 'Locality_223', 'Locality_368',
       'Locality_480', 'Locality_485', 'Locality_398', 'Locality_305',
       'Locality_114', 'Locality_202', 'Locality_96', 'Locality_295',
       'Locality_58', 'Locality_484', 'Locality_323', 'Locality_432',
       'Locality_273', 'Locality_458', 'Locality_150', 'Locality_238',
       'Locality_494', 'Locality_464', 'Locality_431', 'Locality_125',
       'Locality_218', 'Locality_112', 'Locality_27', 'Locality_40',
       'Locality_457', 'Locality_64', 'Locality_372', 'Locality_76',
       'Locality_412', 'Locality_169', 'Locality_479', 'Locality_121',
       'Locality_128', 'Locality_145', 'Locality_205', 'Locality_353',
       'Locality_387', 'Locality_278', 'Locality_258', 'Locality_418',
       'Locality_436', 'Locality_92', 'Locality_39', 'Locality_473',
       'Locality_63', 'Locality_12', 'Locality_498', 'Locality_356',
       'Locality_314', 'Locality_1', 'Locality_394', 'Locality_187',
       'Locality_420', 'Locality_181', 'Locality_179', 'Locality_180',
       'Locality_326', 'Locality_384', 'Locality_430', 'Locality_363',
       'Locality_83', 'Locality_435', 'Locality_442', 'Locality_397',
       'Locality_211', 'Locality_53', 'Locality_172', 'Locality_132',
       'Locality_422', 'Locality_120', 'Locality_280', 'Locality_240',
       'Locality_30', 'Locality_189', 'Locality_111', 'Locality_52',
       'Locality_57', 'Locality_59', 'Locality_88', 'Locality_49',
       'Locality_255', 'Locality_252', 'Locality_171', 'Locality_103',
       'Locality_331', 'Locality_95', 'Locality_18', 'Locality_383',
       'Locality_334', 'Locality_434', 'Locality_129', 'Locality_93',
       'Locality_477', 'Locality_61', 'Locality_281', 'Locality_55',
       'Locality_250', 'Locality_139', 'Locality_90', 'Locality_341',
       'Locality_463', 'Locality_43', 'Locality_386', 'Locality_251',
       'Locality_491', 'Locality_3', 'Locality_141', 'Locality_23',
       'Locality_231', 'Locality_396', 'Locality_478', 'Locality_146',
       'Locality_493', 'Locality_105', 'Locality_98', 'Locality_350',
       'Locality_138', 'Locality_263', 'Locality_38', 'Locality_221',
       'Locality_220', 'Locality_276', 'Locality_451', 'Locality_100',
       'Locality_391', 'Locality_219', 'Locality_337', 'Locality_65',
       'Locality_476', 'Locality_99', 'Locality_402', 'Locality_296',
       'Locality_182', 'Locality_210', 'Locality_333', 'Locality_89',
       'Locality_206', 'Locality_283', 'Locality_160', 'Locality_191',
       'Locality_450', 'Locality_405', 'Locality_67', 'Locality_417',
       'Locality_68', 'Locality_24', 'Locality_164', 'Locality_338',
       'Locality_192', 'Locality_261', 'Locality_360', 'Locality_400',
       'Locality_140', 'Locality_162', 'Locality_243', 'Locality_272',
       'Locality_259', 'Locality_414', 'Locality_452', 'Locality_21',
       'Locality_56', 'Locality_201', 'Locality_224', 'Locality_234',
       'Locality_213', 'Locality_489', 'Locality_208', 'Locality_256',
       'Locality_358', 'Locality_173', 'Locality_34', 'Locality_222',
       'Locality_248', 'Locality_188', 'Locality_377', 'Locality_274',
       'Locality_152', 'Locality_85', 'Locality_142', 'Locality_291',
       'Locality_209', 'Locality_190', 'Locality_168', 'Locality_445',
       'Locality_35', 'Locality_166', 'Locality_225', 'Locality_26',
       'Locality_301', 'Locality_158', 'Locality_320', 'Locality_239',
       'Locality_447', 'Locality_175', 'Locality_390', 'Locality_455',
       'Locality_461', 'Locality_135', 'Locality_134', 'Locality_266',
       'Locality_488', 'Locality_77', 'Locality_332', 'Locality_81',
       'Locality_351', 'Locality_41', 'Locality_423', 'Locality_330',
       'Locality_4', 'Locality_404', 'Locality_249', 'Locality_177',
       'Locality_392', 'Locality_374', 'Locality_17', 'Locality_13',
       'Locality_5', 'Locality_399', 'Locality_379', 'Locality_293',
       'Locality_149', 'Locality_157', 'Locality_270', 'Locality_153',
       'Locality_42', 'Locality_196', 'Locality_37', 'Locality_304',
       'Locality_110', 'Locality_440', 'Locality_409', 'Locality_446',
       'Locality_437', 'Locality_174', 'Locality_319', 'Locality_108',
       'Locality_359', 'Locality_184', 'Locality_16', 'Locality_183',
       'Locality_288', 'Locality_130', 'Locality_14', 'Locality_244',
       'Locality_154', 'Locality_48', 'Locality_19', 'Locality_15',
       'Locality_86', 'Locality_343', 'Locality_376', 'Locality_33',
       'Locality_497', 'Locality_381', 'Locality_257', 'Locality_11',
       'Locality_118', 'Locality_285', 'Locality_10', 'Locality_228',
       'Locality_496', 'Locality_475', 'Locality_317', 'Locality_73',
       'Locality_115', 'Locality_425', 'Locality_346', 'Locality_66',
       'Locality_282', 'Locality_340', 'Locality_471', 'Locality_495',
       'Locality_194', 'Locality_107', 'Locality_482', 'Locality_406',
       'Locality_339', 'Locality_45', 'Locality_70', 'Locality_25',
       'Locality_357', 'Locality_195', 'Locality_31', 'Locality_364',
       'Locality_163', 'Locality_499', 'Locality_144', 'Locality_78',
       'Locality_352', 'Locality_439', 'Locality_284', 'Locality_101',
       'Locality_279', 'Locality_176', 'Locality_87', 'Locality_318',
       'Locality_20', 'Locality_80', 'Locality_468', 'Locality_472',
       'Locality_365', 'Locality_312', 'Locality_133', 'Locality_375',
       'Locality_22', 'Locality_407', 'Locality_193', 'Locality_443',
       'Locality_47', 'Locality_161', 'Locality_348', 'Locality_426',
       'Locality_29', 'Locality_438', 'Locality_6', 'Locality_28',
       'Locality_82', 'Locality_297', 'Locality_401', 'Locality_316',
       'Locality_109', 'Locality_155', 'Locality_481', 'Locality_102',
       'Locality_289', 'Locality_113', 'Locality_492', 'Locality_370',
       'Locality_131', 'Locality_292', 'Locality_362', 'Locality_137',
       'Locality_380', 'Locality_421', 'Locality_378', 'Locality_197',
       'Locality_327', 'Locality_7', 'Locality_106', 'Locality_186',
       'Locality_325', 'Locality_203', 'Locality_449', 'Locality_233',
       'Locality_236', 'Locality_229', 'Locality_170', 'Locality_212',
       'Locality_207', 'Locality_245', 'Locality_388', 'Locality_474',
       'Locality_200', 'Locality_51', 'Locality_178', 'Locality_300',
       'Locality_328', 'Locality_242', 'Locality_410', 'Locality_345',
       'Locality_165', 'Locality_277', 'Locality_46', 'Locality_416',
       'Locality_71', 'Locality_329', 'Locality_465', 'Locality_290',
       'Locality_104', 'Locality_116', 'Locality_444', 'Locality_448',
       'Locality_342', 'Locality_315', 'Locality_373', 'Locality_230',
       'Locality_9', 'Locality_453', 'Locality_198', 'Locality_460',
       'Locality_119', 'Locality_217', 'Locality_306', 'Locality_411',
       'Locality_126', 'Locality_215', 'Locality_433', 'Locality_467',
       'Locality_424', 'Locality_313', 'Locality_371', 'Locality_271',
       'Locality_60', 'Locality_8', 'Locality_336', 'Locality_185',
       'Locality_413', 'Locality_354', 'Locality_395', 'Locality_344',
       'Locality_456', 'Locality_32', 'Locality_226', 'Locality_2',
       'Locality_117', 'Locality_275', 'Locality_303', 'Locality_69',
       'Locality_366', 'Locality_483', 'Locality_214', 'Locality_321',
       'Locality_408', 'Locality_123', 'Locality_349', 'Locality_311',
       'Locality_500', 'Locality_62', 'Locality_124', 'Locality_389',
       'Locality_54', 'Locality_469', 'Locality_294', 'Locality_204',
       'Locality_36', 'Locality_44', 'Locality_487', 'Locality_415',
       'Locality_299', 'Locality_310', 'Locality_269', 'Locality_441',
       'Locality_156', 'Locality_428', 'Locality_324', 'Locality_91',
       'Locality_235', 'Locality_486', 'Locality_79', 'Locality_302',
       'Locality_470', 'Locality_97', 'Locality_347', 'Locality_199',
       'Locality_237', 'Locality_335', 'Locality_307', 'Locality_94',
       'Locality_403', 'Locality_309', 'Locality_419', 'Locality_298',
       'Locality_260', 'Locality_322', 'Locality_308', 'Locality_367',
       'Locality_247', 'Locality_268', 'Locality_264', 'Locality_127',
       'Locality_147', 'Locality_267', 'Locality_361', 'Locality_216',
       'Locality_427', 'Locality_253', 'Locality_429', 'Locality_72'],
      dtype=object)

In [440]:
# Replacing Locality data with locality number only
def extract_locality_number(val):
  val_list = val.split("_")
  return int(val_list[1])

df['Locality'] = df['Locality'].apply(lambda x: extract_locality_number(x))
df['Locality']

0          84
1         490
2         167
3         393
4         466
         ...
249995    187
249996    348
249997    225
249998    138
249999    268
Name: Locality, Length: 250000, dtype: int64

In [441]:
# Stats about property location
print("Property Location Stats")
df[['State','City','Locality']].describe(include='all')

Property Location Stats

         State        City       Locality
count   250000      250000  250000.000000
unique      20          42            NaN
top     Odisha  Coimbatore            NaN
freq     12681        6461            NaN
mean       NaN         NaN     250.399508
std        NaN         NaN     144.544014
min        NaN         NaN       1.000000
25%        NaN         NaN     125.000000
50%        NaN         NaN     250.000000
75%        NaN         NaN     376.000000
max        NaN         NaN     500.000000

### Property Specification Stats Columns

In [442]:
# Property Type column
print("Property Type Stats")
print(df['Property_Type'].describe())
print('')
# List of Property Types
print("Property Types: ", df['Property_Type'].unique())

Property Type Stats
count     250000
unique         3
top        Villa
freq       83744
Name: Property_Type, dtype: object

Property Types:  ['Apartment' 'Independent House' 'Villa']

In [443]:
# Stats about BHK
print("Property BHK stats")
print(df['BHK'].describe())
print('')
print(f"BHK Types: {df['BHK'].unique()}")

Property BHK stats
count    250000.000000
mean          2.999396
std           1.415521
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
Name: BHK, dtype: float64

BHK Types: [1 3 2 4 5]

In [444]:
# Stats about Sqft
print("Property Size(In Sqft) Stats")
df['Size_in_SqFt'].describe()

Property Size(In Sqft) Stats

count    250000.000000
mean       2749.813216
std        1300.606954
min         500.000000
25%        1623.000000
50%        2747.000000
75%        3874.000000
max        5000.000000
Name: Size_in_SqFt, dtype: float64

In [445]:
# Stats about Price
print("Property Price(In Lakhs) Stats")
df['Price_in_Lakhs'].describe()

Property Price(In Lakhs) Stats

count    250000.000000
mean        254.586854
std         141.349921
min          10.000000
25%         132.550000
50%         253.870000
75%         376.880000
max         500.000000
Name: Price_in_Lakhs, dtype: float64

In [446]:
# Stats about Price per Sqft
print("Price Per SqFt(In Lakhs) Stats")
df['Price_per_SqFt'].describe()

Price Per SqFt(In Lakhs) Stats

count    250000.000000
mean          0.130597
std           0.130747
min           0.000000
25%           0.050000
50%           0.090000
75%           0.160000
max           0.990000
Name: Price_per_SqFt, dtype: float64

In [470]:
existing_df = df['Price_per_SqFt']
cal_df = ((df['Price_in_Lakhs']) * 100000 / (df['Size_in_SqFt']) / 100000).round(3)

In [471]:
cal_df

0         0.103
1         0.083
2         0.050
3         0.110
4         0.038
          ...
249995    0.138
249996    0.006
249997    0.081
249998    0.123
249999    0.046
Length: 250000, dtype: float64

In [472]:
cal_df.describe()

count    250000.000000
mean          0.130583
std           0.130719
min           0.002000
25%           0.048000
50%           0.092000
75%           0.160000
max           0.992000
dtype: float64

In [449]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='object')